apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-deployment
  namespace: morinlandon
spec:
  selector:
    matchLabels:
      app: house-api
  replicas: 1
  template:
    metadata:
      labels:
        app: house-api
    spec:
      initContainers:
      - name: init-redis
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup redis-service; do echo waiting for redis; sleep 2; done"]
      containers:
      - name: house-api
        image: lab4:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "service-redis"
        - name: REDIS_PORT
          value: "6379"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          terminationGracePeriodSeconds: 60


